name: 🐛 Bug Report
description: Report a bug or issue with a theme
title: "🐛 Bug: "
labels: ["bug"]
assignees:
  - estrogenhrt
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us fix the issue quickly.

  - type: dropdown
    id: theme_name
    attributes:
      label: Which theme is affected?
      description: Select the theme you're experiencing issues with
      options:
        - Cyberpunk
        - Minecraft
        - Miku
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: A clear and detailed description of what the bug is
      placeholder: |
        Example: The chat background is completely black instead of dark gray, making text hard to read.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: |
        Example: The chat background should be dark gray (#2b2d31) with white text that's easy to read.
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: |
        Example: The chat background is pure black (#000000) and text is barely visible.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Install the theme
        2. Navigate to a server
        3. Open a text channel
        4. Notice the black background
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - Vencord
        - BetterDiscord
        - Both
    validations:
      required: true

  - type: dropdown
    id: discord_client
    attributes:
      label: Discord Client
      description: Which Discord client are you using?
      options:
        - Discord Desktop (Stable)
        - Discord Desktop (PTB)
        - Discord Desktop (Canary)
        - Discord Web
        - Vesktop
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: "e.g., Windows 11, macOS 14.2, Ubuntu 22.04, iOS 17, Android 14"
    validations:
      required: true

  - type: input
    id: theme_version
    attributes:
      label: Theme Version
      description: Which version of the theme are you using? (if known)
      placeholder: "e.g., v1.2.3 or 'latest'"

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Add screenshots or videos showing the bug (drag and drop or paste images here)
      placeholder: |
        Tip: You can drag and drop images directly into this text box!

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information that might help us fix this bug
      placeholder: |
        - Does this happen with other themes?
        - Did this work before a recent update?
        - Are you using any other themes or plugins?
        - Any other relevant information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this bug hasn't been reported already
          required: true
        - label: I have tested this with the latest version of the theme
          required: true
        - label: I have disabled other themes to confirm this issue is specific to this theme
          required: false
        - label: I have included screenshots or videos demonstrating the issue
          required: false
